package menus

import "github.com/richardwilkes/unison"

// Menu, Item & Action IDs
const (
	NewFileMenuID = unison.UserBaseID + iota
	NewSheetItemID
	NewTemplateItemID
	NewAdvantagesLibraryItemID
	NewAdvantageModifiersLibraryItemID
	NewEquipmentLibraryItemID
	NewEquipmentModifiersLibraryItemID
	NewNotesLibraryItemID
	NewSkillsLibraryItemID
	NewSpellsLibraryItemID
	OpenItemID
	RecentFilesMenuID
	SaveItemID
	SaveAsItemID
	ExportToMenuID
	PrintItemID
	UndoItemID
	RedoItemID
	DuplicateItemID
	ConvertToContainerItemID
	StateMenuID
	ToggleStateItemID
	IncrementItemID
	DecrementItemID
	IncrementUsesItemID
	DecrementUsesItemID
	IncrementSkillLevelItemID
	DecrementSkillLevelItemID
	IncrementTechLevelItemID
	DecrementTechLevelItemID
	SwapDefaultsItemID
	JumpToSearchItemID
	ItemMenuID
	AdvantagesMenuID
	NewAdvantageItemID
	NewAdvantageContainerItemID
	NewAdvantageModifierItemID
	NewAdvantageContainerModifierItemID
	AddNaturalAttacksAdvantageItemID
	SkillsMenuID
	NewSkillItemID
	NewSkillContainerItemID
	NewTechniqueItemID
	NewSpellItemID
	NewSpellContainerItemID
	NewRitualMagicSpellItemID
	EquipmentMenuID
	NewCarriedEquipmentItemID
	NewCarriedEquipmentContainerItemID
	NewOtherEquipmentItemID
	NewOtherEquipmentContainerItemID
	NewEquipmentModifierItemID
	NewEquipmentContainerModifierItemID
	NotesMenuID
	NewNoteItemID
	NewNoteContainerItemID
	OpenEditorItemID
	CopyToSheetItemID
	CopyToTemplateItemID
	ApplyTemplateItemID
	OpenOnePageReferenceItemID
	OpenEachPageReferenceItemID
	LibraryMenuID
	SettingsMenuID
	PerSheetSettingsItemID
	PerSheetAttributeSettingsItemID
	PerSheetBodyTypeSettingsItemID
	DefaultSheetSettingsItemID
	DefaultAttributeSettingsItemID
	DefaultBodyTypeSettingsItemID
	GeneralSettingsItemID
	PageRefMappingsItemID
	ColorSettingsItemID
	FontSettingsItemID
	MenuKeySettingsItemID
	SponsorGCSDevelopmentItemID
	MakeDonationItemID
	UpdateAppItemID
	ReleaseNotesItemID
	WebSiteItemID
	MailingListItemID
	ChangeLibraryLocationsItemID
	LibraryBaseItemID
)
